# Main configuration for ROG Strix G16
# This file orchestrates all modules
{
  inputs,
  lib,
  config,
  pkgs,
  ...
}: {
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Modular configuration
    ./system      # Boot, disk, locale
    ./hardware    # NVIDIA, ASUS, audio
    ./desktop     # Plasma, portals
    ./programs    # Gaming, development
    ./services    # Maintenance, power
  ];

  # Nixpkgs configuration
  nixpkgs = {
    overlays = [
      inputs.self.overlays.additions
      inputs.self.overlays.modifications
      inputs.self.overlays.unstable-packages
    ];
    config = {
      allowUnfree = true;
    };
  };

  # Nix settings
  nix = let
    flakeInputs = lib.filterAttrs (_: lib.isType "flake") inputs;
  in {
    settings = {
      experimental-features = "nix-command flakes";
      flake-registry = "";
      nix-path = config.nix.nixPath;
      # TODO: Add CachyOS binary cache when using CachyOS kernel
      # substituters = ["https://chaotic-nyx.cachix.org"];
      # trusted-public-keys = ["chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8="];
    };
    channel.enable = false;
    registry = lib.mapAttrs (_: flake: {inherit flake;}) flakeInputs;
    nixPath = lib.mapAttrsToList (n: _: "${n}=flake:${n}") flakeInputs;
  };

  # Hostname
  networking.hostName = "rog-strix";

  # User configuration
  users.users.jens = {
    isNormalUser = true;
    description = "Jens";
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
      "audio"
      # TODO: Add these groups as you enable the services:
      # "docker"
      # "libvirtd"
    ];
    # TODO: Set initial password or use passwordFile
    # initialPassword = "changeme";
  };

  # Enable zsh system-wide (required for user shell)
  programs.zsh.enable = true;

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  system.stateVersion = "24.05";
}

