# Main configuration for ROG Strix G16
# This file orchestrates all modules
{
  inputs,
  lib,
  config,
  pkgs,
  ...
}: {
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Modular configuration
    ./system      # Boot, disk, locale
    ./hardware    # NVIDIA, ASUS, audio
    ./desktop     # Plasma, portals
    ./programs    # Gaming, development
    ./services    # Maintenance, power
  ];

  # Nixpkgs configuration
  nixpkgs = {
    overlays = [
      inputs.self.overlays.additions
      inputs.self.overlays.modifications
      inputs.self.overlays.stable-packages
      inputs.chaotic.overlays.default  # CachyOS packages overlay
    ];
    config = {
      allowUnfree = true;
    };
  };

  # Nix settings
  nix = let
    flakeInputs = lib.filterAttrs (_: lib.isType "flake") inputs;
  in {
    settings = {
      experimental-features = "nix-command flakes";
      flake-registry = "";
      nix-path = config.nix.nixPath;
      # Binary caches for precompiled packages (order matters - checked first to last)
      substituters = [
        "https://cache.nixos.org"  # Official NixOS cache
        "https://chaotic-nyx.cachix.org"  # Chaotic-nyx packages (includes CachyOS kernel)
      ];
      trusted-public-keys = [
        "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="  # Official NixOS
        "chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8="  # Chaotic-nyx
      ];
    };
    channel.enable = false;
    registry = lib.mapAttrs (_: flake: {inherit flake;}) flakeInputs;
    nixPath = lib.mapAttrsToList (n: _: "${n}=flake:${n}") flakeInputs;
  };

  # Hostname
  networking.hostName = "rog-strix";

  # User configuration
  users.users.jens = {
    isNormalUser = true;
    description = "Jens";
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
      "audio"
      # TODO: Add these groups as you enable the services:
      "docker"
      # "libvirtd"
    ];
    # Password: Set one of the following:
    # Option 1: Set initial password (will be prompted on first login)
    # initialPassword = "changeme";
    # Option 2: Use password file (more secure, create with: mkpasswd -m sha-512 > /etc/nixos/secrets/jens-password)
    # passwordFile = "/etc/nixos/secrets/jens-password";
    # Option 3: Set password manually after first login: passwd
  };

  # Enable zsh system-wide (required for user shell)
  programs.zsh.enable = true;

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  system.stateVersion = "26.05";
}

